# -*- coding: utf-8 -*-
"""MP3_P3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVL4BNjtoFi3sef3xvYZK9asGn53Aqkz
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

checkerboard_img = cv2.imread('checkerboard.png', cv2.IMREAD_GRAYSCALE)
toy_img = cv2.imread('toy.png', cv2.IMREAD_GRAYSCALE)

def harris_corner_detection(image):
    img_float = np.float32(image)
    dst = cv2.cornerHarris(img_float, 2, 3, 0.04)
    dst = cv2.dilate(dst, None)
    return dst

checkerboard_corners = harris_corner_detection(checkerboard_img)
toy_corners = harris_corner_detection(toy_img)

checkerboard_corners_normalized = cv2.normalize(checkerboard_corners, None, 0, 255, cv2.NORM_MINMAX)
toy_corners_normalized = cv2.normalize(toy_corners, None, 0, 255, cv2.NORM_MINMAX)

plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(checkerboard_corners_normalized, cmap='hot')
plt.title("Checkerboard Corners")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(toy_corners_normalized, cmap='hot')
plt.title("Toy Corners")
plt.axis('off')

plt.show()